spring.application.name=networkcopilot

spring.config.import=optional:file:C:/Users/divsutar/NavPython/Network-Intrusion-detection/Backend/networkcopilot/local.properties

server.port=${PORT:8090}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format-sql:true


spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.chat.max-tokens=10000

spring.ai.model.embedding=none

logging.level.org.springframework.ai.openai=DEBUG
logging.level.com.openai=DEBUG

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

ml.python.path=C:/Users/divsutar/miniconda3/envs/ml/python.exe
ml.script.path=C:/Users/divsutar/NavPython/Network-Intrusion-detection/ml/predict_csv.py
ml.pipeline.path=C:/Users/divsutar/NavPython/Network-Intrusion-detection/ml/pipeline.py
ml.service.url=http://localhost:8000/predict