spring.application.name=networkcopilot

spring.config.import=optional:file:C:/Users/divsutar/NavPython/Network-Intrusion-detection/Backend/networkcopilot/local.properties

server.port=${PORT:8090}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format-sql:true


spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.chat.model=nvidia/nemotron-3-ultra-550b-a55b
spring.ai.openai.chat.options.max-tokens=1000

spring.ai.model.embedding=none

logging.level.org.springframework.ai.openai=DEBUG
logging.level.com.openai=DEBUG